### ISSUE TITLE
System comands of the plugin 

### ISSUE THREAD

**Issue by ScharV** [ralmn/OctoPrint-Ikea-tradfri#14]
Is there a way to use the Plugin with System comands trough command line? Would be nice to have the system comands for on and off.
Thanks for this great plugin 🤙🏼

**Comment by ralmn** [comment]
I will look how do that :) 
But as workaround you can use the api with curl : `curl -v -X POST https://<octoprint url>api/plugin/ikea_tradfri -H "Content-Type: application/json" -d '{"command": "turnOn"}'` and `curl -v -X POST https://<octoprint url>api/plugin/ikea_tradfri -H "Content-Type: application/json" -d '{"command": "turnOff"}'`

**Comment by ralmn** [comment]
Ok i can do that for 1.3 probably (1.2 today or tomorrow)

**Comment by ScharV** [comment]
Yeah that looks great😬 will test it later🤙🏼 Thanks

**Comment by ScharV** [comment]
I use Octopod for iOS mostly so I can use this comands  with System comand editor to switch the outlet through the app🤙🏼

**Comment by ralmn** [comment]
I have add system commands for turn on `octoprint plugins ikea_tradfri:turnon` and turn off `octoprint plugins ikea_tradfri:turnoff` with #18

**Comment by ScharV** [comment]
@ralmn Thanks😍

**Comment by pierrebv** [comment]
Hi. I'm sorry, my question is probably stupid, but… I just installed _Custom Control Editor_ and I would like to add a button to turn my outlet on from OctoPod. But I basicaly… don't kown how to use _Custom Control Editor_, apparently. 

I tried to put `octoprint plugins ikea_tradfri:turnon`, or just `ikea_tradfri:turnon`, as good as `curl -v -X POST https://<octoprint url>api/plugin/ikea_tradfri -H "Content-Type: application/json" -d '{"command": "turnOn"}'`, as a _Command_ or a _Script Command_ on _Custom Control Editor_, but each time, the brand new button is not active on Octprint and OctoPod say it's not working because the printer is offline (surprise!).

<img width="576" alt="Capture d’écran 2021-11-26 à 19 05 29" src="https://user-images.githubusercontent.com/28785026/143618670-504bc890-c52e-478a-9e6c-c34230ce7533.png">


I understand I'm writing something to be sent to the printer, while I want to send this command to Octoprint instead. 

I would be ready to believe that's not possible, but this topic and request prove it's possible (my researches drove me originally to this topic, then I downloaded _CCE_ because I'm not confident enough to edit _config.yaml_ by myself). I just don't understand how / I'm probably just missing a little thing. If someone could help me…
